highcharts:
  jshead:
    - js/jquery-1.9.1.min.js
    - js/highcharts.js
    - js/highcharts-more.js
    - js/heatmap.js
    - js/highcharts-3d.js
    - js/exporting.js
    - js/solid-gauge.src.js
  cdn:
    jshead:
      - "http://code.jquery.com/jquery-1.9.1.min.js"
      - "http://code.highcharts.com/highcharts.js"
      - "http://code.highcharts.com/highcharts-more.js"
      - "http://code.highcharts.com/modules/heatmap.js"
      - "http://code.highcharts.com/highcharts-3d.js"
      - "http://code.highcharts.com/modules/exporting.js"
      - "http://code.highcharts.com/modules/solid-gauge.src.js"
